public static class UserStatuses
{
    public const string Default = "🟢 Available";

    public static readonly HashSet<string> Allowed =
    [
        "🟢 Available",
        "💻 Online",
        "🛠️ Working",
        "🎯 Focused",
        "🧠 Heads-down",
        "✅ On task",
        "⚡ Active",
        "🆓 Free",
        "🔴 Busy",
        "📅 In a meeting",
        "🎤 Presenting",
        "📞 On a call",
        "🔕 Do not disturb",
        "🧑‍💻 Deep work",
        "⛔ Blocked",
        "🔄 Context switching",
        "🍽️ Eating",
        "🔨 In progress",
        "👀 Reviewing",
        "💻 Coding",
        "🧪 Testing",
        "🐞 Debugging",
        "🎨 Designing",
        "🔍 Researching",
        "📝 Documenting",
        "⏳ Waiting for input",
        "✅ Waiting for approval",
        "🏠 Working from home",
        "🏢 In office",
        "🌍 Remote",
        "✈️ Traveling",
        "🔜 Back soon",
        "🚶 Stepped away",
        "🕒 Away briefly",
        "🐢 Delayed response",
        "⏱️ Limited availability",
        "🌴 Out of office (OOO)",
        "🏖️ On vacation",
        "🤒 Sick leave",
        "🧑‍⚕️ Personal leave",
        "🎉 Holiday",
        "🛌 Day off",
        "🚧 Blocked by dependency",
        "🤝 Waiting on another team",
        "🧑‍💼 Waiting on customer",
        "📋 Awaiting requirements",
        "⚫ Offline",
        "❓ Unknown",
        "🆕 Onboarding",
        "📟 On-call",
        "🌙 After hours"
    ];
}

